name: sweet_pal
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  app_links: ^6.4.1
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.5
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  email_validator: ^3.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.3.1
  flutter_map: ^8.2.1
  flutter_paypal: ^0.2.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get_it: ^8.2.0
  google_maps_flutter: ^2.12.3
  image_picker: ^1.2.0
  latlong2: ^0.9.1
  modal_progress_hud_nsn: ^0.5.1
  smooth_page_indicator: ^1.2.1
  supabase_flutter: ^2.9.1
  shared_preferences: ^2.4.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/g14.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/g14.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
